# Generated by Django 2.2.5 on 2021-02-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
